version: '3.8'

services:
  meu_app2:
    build:
      context: ./nginx
      dockerfile: Dockerfile
    restart: unless-stopped
    volumes:
      - ./volumes/horarios-pagantes:/var/www/html
    container_name: meu_app
    environment:
      - VIRTUAL_HOST=caixapreta.app
      - LETSENCRYPT_HOST=caixapreta.app
      - LETSENCRYPT_EMAIL=nicollasacruz@gmail.com
      - VIRTUAL_PORT=8081
    depends_on:
      - php2
    networks:
      - minha_rede2
      - reverse-proxy

  php2:
    build:
      context: ./php
      dockerfile: Dockerfile
    restart: unless-stopped
    ports:
      - "5173:5173"
    volumes:
      - ./volumes/horarios-pagantes:/var/www/html
    networks:
      - minha_rede2

  db2:
    image: mariadb
    environment:
      - TZ=${TZ:-CET}
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD:-root}
      - MYSQL_DATABASE=${MYSQL_DATABASE:-horarios}
      - MYSQL_USER=${MYSQL_USER:-horarios}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD:-horarios}
    volumes:
      - ./.docker/config/mysql:/etc/mysql/conf.d
      - ./volumes/mysql/data:/var/lib/mysql
    restart: unless-stopped
    ports:
      - "3306:3306"
    networks:
      - minha_rede2
    
  redis2:
    image: redis:latest
    restart: unless-stopped
    networks:
      - minha_rede2

networks :
  minha_rede2:
    external: true
  reverse-proxy:
    external: true
    name: reverse-proxy
