version: '3.8'

services:

  meu_app:
    build:
      context: ./nginx
      dockerfile: Dockerfile
    restart: unless-stopped
    ports:
      - "8080:8080"
      # - "80:80"
      # - "5173:5173"
    volumes:
      - ./volumes/horarios-pagantes:/var/www/html
    container_name: meu_app
    environment:
      - VIRTUAL_HOST=horariospagantes.vip
      - VIRTUAL_PORT=8080
    depends_on:
      - php
    networks:
      - minha_rede

  php:
    build:
      context: ./php
      dockerfile: Dockerfile
    restart: unless-stopped
    ports:
      - "5173:5173"
    volumes:
      - ./volumes/horarios-pagantes:/var/www/html
    networks:
      - minha_rede

  db:
    image: mariadb
    environment:
      - TZ=${TZ:-CET}
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD:-root}
      - MYSQL_DATABASE=${MYSQL_DATABASE:-horarios}
      - MYSQL_USER=${MYSQL_USER:-horarios}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD:-horarios}
    volumes:
      - ./.docker/config/mysql:/etc/mysql/conf.d
      # - ./volumes/mysql/dump:/docker-entrypoint-initdb.d
      - ./volumes/mysql/data:/var/lib/mysql
    restart: unless-stopped
    ports:
      - "3306:3306"
    networks:
      - minha_rede
    
  mailhog:
    image: blueimp/mailhog
    ports:
      - 8025:8025
      - 1025:1025
    networks:
      - minha_rede
  
  redis:
    image: redis:latest
    restart: unless-stopped
    networks:
      - minha_rede

networks :
  minha_rede:
    external: true